version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8005
    # Ensure backend is accessible by frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Default Vite dev server port
    volumes:
      - ./frontend:/app
      - /app/node_modules # Anonymous volume to prevent host node_modules from overwriting container's
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
